### ISSUE TITLE
Data Organization

### ISSUE THREAD

**Issue by nicholas-david** [healthysustainablecities/global-indicators#109]
@gboeing @carlhiggs 

For the process data, the data organization on cloudstor is a little confusing. I think it would be positive if all the data could be downloaded in one click. That would involve moving the old input data out of the input folder, and incorporating the most recent GTFS data into the input folder. Please let me know your thoughts. I will make sure to update the documentation according to what you implement.

**Comment by gboeing** [comment]
@carlhiggs @nicholas-david does this issue remain open or should we close it out?

**Comment by carlhiggs** [comment]
Hi @nicholas-david @gboeing , Apologies if my response to this issue was lost in the summer leave period over Christmas/New Years; I remember seeing it at some point and intending to respond.  I had some memory we had discussed this but having said that it seems I haven't responded here and I couldn't find anything in e-mails.  

Currently the CloudStor folder for the Global Indicators data looks like this:
![image](https://user-images.githubusercontent.com/12984626/115314944-95d94d00-a1b9-11eb-95ae-bc720d51d211.png)

In principle, this folder should be able to be downloaded as a zip file in one go by selecting all files/subfolders and clicking download; the idea is then to extract it to the process/data folder, where the 'GTFS' folder will merge with the existing sub-folder in the repository (there are some configuration aspects relating to GTFS that are drawn upon by the code, hence need for the place holder sub-folder).  The GTFS folder, the GHS folder, and the boundaries are all data resources used by the project; while the 'input' and 'output' folders are for processed city-specific resources, and the final combined outputs.  

I would be reluctant to change the file structure now (eg moving GTFS into the city-specific input sub-folder), as this could mess with some code dependencies.  The input and output folders could be renamed to 'processed_inputs' and 'processed_outputs' (if other parts of code pointing to these are modified), since these resources are generated as part of the scripted "pre-process" and "process" (which is really just one process); the pre-processing stage uses the resources in the data folder to generate those resources in the so-called 'input' folder.

Regarding the data on CloudStor though, it is a good point that our archival versions of city-specific input and output resources from earlier stages of the project could be moved from this folder so it just retains what is needed/has been generated for the main project analysis. 

For publication of our article, I wonder if we should locate our 'data' resources on a public repository like Figshare?

**Comment by gboeing** [comment]
> I would be reluctant to change the file structure now (eg moving GTFS into the city-specific input sub-folder), as this could mess with some code dependencies.

Let's leave it as is.

> For publication of our article, I wonder if we should locate our 'data' resources on a public repository like Figshare?

I think that's a great idea, assuming any partner-provided data are shareable.

**Comment by carlhiggs** [comment]
Thinking further about this, the empty 'study_region' folder on CloudStor reminded me about a slight dis-junct between the 'pre-process' and 'process' steps, which we could address to make things clearer.  The pre-process step exports geopackages to a sub-folder 'study_region', which I think makes more descriptive sense than 'input' (because as you point out @nicholas-david, most of the resources in the data folder are inputs, except for the outputs). Currently, the resources must be manually moved from study_region to 'input'.  

It would be relatively easy to change the pre-process export script to export to 'data/input'.  However, I think it may help things make more sense to rename the 'data/input' folder in the configuration script to 'data/study_region'.  This would involve changes on lines 113, 164, 186, 187 of  setup_config.py where this subfolder is referenced; the 'input' folder name should really be parameterised there so it is just referenced once in any case in a single parameter.

I would be happy to make this change if all (eg @shiqin-liu @gboeing @nicholas-david) are happy; I think it will make the continuity between 'pre-process' and 'process' more obvious, and hopefully better address your concerns @nicholas-david. 

Let me know if you think this is a good idea, and I'll do it!

Regarding the data licencing question, good point; I'll look to make a summary of our data resources for our next meeting and we can discuss if we think there are any items with licencing concerns and go from there.

**Comment by gboeing** [comment]
Sounds like a good idea.

**Comment by shiqin-liu** [comment]
Sounds good to me too :)

**Comment by carlhiggs** [comment]
Great! I committed changes for this earlier today, as per above.  In advertantly, as per message elsewhere i did this to the main branch.   The data on CloudStor has been simplified as discussed too. So I think we can close this, and I'll do that now.
