### ISSUE TITLE
Incompatible version of sphinxcontrib-bibtex

### ISSUE THREAD

**Issue by VuokkoH** [healthysustainablecities/global-indicators#134]
Hi!

Running [_create_preliminary_validation_report.py](https://github.com/global-healthy-liveable-cities/global-indicators/blob/main/process/pre_process/_create_preliminary_validation_report.py) in the default environment results in ExtensionError: `You must configure the bibtex_bibfiles setting`. 

Seems that the latest version of `sphinxcontrib-bibtex` is incompatible with some other stuff. 

I now manually downgraded to `sphinxcontrib-bibtex==1.0.0` and managed to build the PDF, but apparently a better fix would be to restrict the package vesrion in `requirements.txt` like this: `sphinxcontrib-bibtex<2.0.0` as discussed in here: https://github.com/executablebooks/jupyter-book/issues/1137.

Cheers :)

**Comment by carlhiggs** [comment]
Thanks Vuokko, just wanted to add a comment here because I know we discussed this via e-mail --- but want to acknowledge here that i've read this, and aim to get around to looking at this shortly!  I expect we'll do some small patches for incompatibilities that have arisen such as this, before commencing a bigger re-factoring of the tools and code.  Thanks for noting this issue, and for patience :)

**Comment by carlhiggs** [comment]
I just noticed on one of my computers that hadn't updated the Docker image with the new requirements that a better fix may be to add `bibtex_bibfiles = ['references.bib']` in process/collaborator_report/conf_template.py ----- as per usage notes for sphinxcontrib-bibtex https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html .  I confirmed that this allowed the process to run with version 2.3.0.

That means that setting version < 2.0.0 probably isn't required and could be avoided; I'll aim to update the Docker image when simplifying things in a future update and will keep this in mind!
