### ISSUE TITLE
Consider if its possible to model routing for pedestrian areas 

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#161]
It was pointed out to me (thanks @IrenaItova!) that the pedestrian network we generate didn't include the following pedestrian 'area'
https://www.openstreetmap.org/way/614403840#map=19/53.55885/-2.32512
![image](https://user-images.githubusercontent.com/12984626/197396488-fd9e0e13-93b1-4924-8d6f-d449ffe47ef9.png)

I looked at our custom pedestrian query and determined that this is most likely because the area is tagged with 'area=yes' in addition to being 'highway=pedestrian'.

Our custom pedestrian query filters out such areas (["area"!~"yes"]), being based on the network types defined as defaults in Osmnx (i.e. https://github.com/gboeing/osmnx/blob/main/osmnx/downloader.py#L67 )

So, it makes me wonder, what if we removed that filter?   

Presumably there's a reason such areas would be/have been filtered out, but I'll leave this issue here for us to think about if this change could improve modelling for pedestrian accessibility (any thoughts @gboeing?)

**Comment by gboeing** [comment]
Yes OSMnx by default ignores ways with `area=yes` in its built-in [filters](https://github.com/gboeing/osmnx/blob/main/osmnx/downloader.py#L28). This can be customized as needed by the user.

The reasoning behind ignoring these ways is that they don't correspond well to a graph-theoretic representation of the network. That is, these ways represent boundaries of a polygon. However, OSMnx graphs expect ways to represent links between intersections/dead-ends. If you *don't* filter out `area=yes` ways, you can model them in your graph, but it'll be a bit odd because you cannot route "through" these areas, only "around" them on their polygonal boundary ways.

**Comment by carlhiggs** [comment]
Thanks @gboeing , I knew there would be a reason!

Something to think about for our project some time when we have more time perhaps.  I've thought of this before in the context of public open space --- often (not always) people can/would walk through these, and it could be nice to model that assumption (although it would sometimes be wrong) by inserting new edges across to represent their potential for being traversed.    I never ended up looking too far into that because the assumption seemed a bit off (eg many public open spaces are fenced at least on some sides).  But maybe it could be safer to implement pseudo-paths cutting through areas tagged with pedestrian=highway?  Maybe i'll think about that for later in the year, or at least evaluate implications of removing the area!=yes filter

Thanks @gboeing and @IrenaItova!

**Comment by carlhiggs** [comment]
As per above discussion, this may be possible in theory; in practice, I don't think we have capacity to think through the implications of any changes.   I think retaining the current usage as per default in OSMnx based on Geoff's reasoning is reasonable for now.  I will close this issue, as it is not likely to be resolved in short/medium term.
