### ISSUE TITLE
OSM: Parameters for pedestrian and transportation infrastructure

### ISSUE THREAD

**Issue by shiqin-liu** [healthysustainablecities/global-indicators#2]
I am wondering how to check parameters for pedestrian or transportation infrastructure in OSM. For now, I search for Wiki [https://wiki.openstreetmap.org/wiki/Highways](url) for the related tag. Not sure if that's an efficient way to do, any other suggestions will be appreciated.

For the pedestrian network, they use that for the previous project:
```
pedestrian = (
             '["area"!~"yes"]' 
             '["highway"!~"motor|proposed|construction|abandoned|platform|raceway"]'
             '["foot"!~"no"]'  
             '["service"!~"private"]' 
             '["access"!~"private"]'
             ) 
```

Just wondering how it compared to `network_type={'walk' , 'cycle'}`.

I try to retain transportation infrastructure, for example `infrastructure='way["public_transport"~"platform"]`, but the result turns out strange. I would like to know what other kinds of transportation infrastructure parameters available there in OSM, what is the best way to quick search about this?  

Maybe we could discuss further with this? It is part of the proposed indicators to consider, like public transport access, ratios of roads to cycle lanes, distance to transit etc.  Also, may need to overlay with related administrative spatial data (if available) to compare how OSM reflects the reality.

**Comment by gboeing** [comment]
You can see OSMnx's various `network_type` filters here: https://github.com/gboeing/osmnx/blob/eb39dff4aaf726d33b6b7aa9f71c50f3e9b9f012/osmnx/core.py#L560

In general, you'll want to use the OSMnx pre-built filters unless there's clear evidence that they're insufficient (in which case, we might want to update them).

Here's a good place to get started with OSM tags: https://wiki.openstreetmap.org/wiki/Tags

You can test queries interactively here: https://overpass-turbo.eu/

**Comment by carlhiggs** [comment]
The pedestrian custom filter I created was really done for our Melbourne context, where due to many shared bike/cycle paths we found exclusion of cycleways seemed problematic for pedestrian path representation; walkble cut throughs through parks, and some bridge crossing weren't included due to being flagged as cyclepaths.  From memory, my custom filter is basically like the OSMnx 'walk' with the cycling exclusion removed. Basically, we felt that in Australia, anywhere a bike can go, a pedestrian can go too; hence combined approach; in Melbourne it appeared to provide a more valid network for our purposes. 

Geoff makes a good point that, while this might make sense in Melbourne or Australia it may not be appropriate in global context.

**Comment by shiqin-liu** [comment]
Thank you for the clarification! So maybe setting the network_type = walk is a more conservative approach to define pedestrian in a global context. At least in the US, some of the bike lanes are in the middle of the road and not designed for walking. But we could always add cycle as another option for comparison. Good to know the context!
