### ISSUE TITLE
GTFS quality verification bug

### ISSUE THREAD

**Issue by ruoyuch** [healthysustainablecities/global-indicators#2]
**Describe the bug**
In `/home/ghsci/process/subprocesses/ghsci.py:801` and `Region._run_data_checks(self)`, the program checks the quality of the GTFS file.  When checking the date, the program does not allow _GTFS feeds without specific start and end date._ This prohibits the situation of **using GTFS feeds without specific start and end dates**.

**To Reproduce**
Leave the start and end dates blank, the bug will be reproduced. 

**Expected behavior**
Specific instructions should be provided on how to deal with the GTFS feeds without specific start and end dates.  The case is rare, but it happened when I was preparing the Los Angeles GTFS files, which have more than 60 different GTFS files.  GTFS feeds without specific start and end dates may face quality issues but are still valuable.

**Screenshots**
<img width="864" alt="Screenshot 2024-06-10 at 01 01 50" src="https://github.com/healthysustainablecities/global-indicators/assets/49519821/802e8694-2b6d-44ac-8197-bf43ec132374">

**Desktop:**
 - OS: MacOS
 - Version 4.5.3

**Comment by ruoyuch** [comment]
At the same time, it seems that the quality checker's date-checking function is not working properly.  When I was putting start_date later than end_date, the checker did not pop up an (expected) error code.

**Comment by carlhiggs** [comment]
Hi Ryoyu,

Code contributions are welcome; in the mean time, does making your end date
one day later than the start work, so it includes your single day?

Cheers,

Carl

**Comment by carlhiggs** [comment]
Just as a follow up, this check (that end date is not before start date) was added because several users had problems running their analyses due to misconfiguration of GTFS.  By adding this check, it warns users before starting analysis that something isn't right.  

I believe in the case of a single day analysis setting the end date the day later than start date would result in day time weekday services being correctly captured, if the single day is a weekday.  If that works as intended, perhaps we can close this issue, as the check may be doing what it means to be doing.  Otherwise, you are welcome to suggest modifications in code, but their may be other priorities if this is more a feature request than a bug.

Another consideration is, if a GTFS feed describes only a single day of service, is it fairly representative of the usual conditions across its service area in a city on day time weekdays across the year?  At the least, it may be a data limitation that should be noted.

Hope this helps @ruoyuch

**Comment by ruoyuch** [comment]
Hi Carl,

Thanks for the clarification.  After your explanation, I agree the checker helps and the way it works is suitable.  If the user cannot get high-quality GTFS data in their case, the proper way might be not to include it.  I will close the issue with the comment.  Thanks for your answer!

Best,
Ruoyu
