### ISSUE TITLE
Should we save output files at this point?

### ISSUE THREAD

**Issue by shiqin-liu** [healthysustainablecities/global-indicators#3]
Should we save the OSM output for Pheonix at this point? For now, I try to save the network output just for experimental purpose. Two quick questions:

1. Should I save graphs as shapefile or GraphML? Not so familiar with GraphML...

2. How can I save in a folder a level up a directory? For example, I am currently under the `process` folder, how can I save the output in a new folder under the parent directory `global-indicator` if using `ox.save_graph_shapefile`?

Let me know if saving the output is not necessary at this point.

Thank you!

**Comment by gboeing** [comment]
Here's a resource for graphml: http://graphml.graphdrawing.org/

Yes we should save to graphml from OSMnx... that's just useful for re-loading later. The filepath would be like `'../myfolder/filename.graphml'`

**Comment by carlhiggs** [comment]
Hey, happy to share my thoughts on these aspects:

1) I've previously saved both: shp files, because I was using an arcpy network analyst approaching which used nodes and edges in this format (depending on approach though may not be necessary for this project?) - I also tend to plonk it in postgis anyway; graphml, because if I've taken the time to download it once (maybe more than a few mins for a big city?) rather than repeat this I can check if saved network exists for say Phoenix --- if so, load_graph using that file, else run to create it (and save, for next time).  For me this is useful when debugging, as I have so many bugs I have to re-run things a lot; nice to have shortcut options!  If saving it, I recommend including date so quick too see time point of OSM retrieval --- when you repeat in 2022, the versions are apparently different at a glance.

2) I've found with my Docker Bangkok approach, if I launch the bash terminal in my root project directory, I can then cd to the code directory (which I may have called process).  From there, depending on what you are doing you can use '../data/file. graphml' to refer to a file in that directory.  If saving a file, you might want to run a check to see if the directory referred to exists, else make it.   I've also noticed though, that some functions may prefer an absolute path, and on Unixl you need to use something like 'file:///path/to/file.graphml' - but I find this a bit tricky, so where possible I use relative paths.   Feel free to grab some of those conditional folder check code from my scripts if you want.

Hope the above can be of help,

Carl
