### ISSUE TITLE
Error after 61% of nodes created

### ISSUE THREAD

**Issue by tiernanmartin** [healthysustainablecities/global-indicators#366]
## Description
_Note: This is not necessarily a bug; it may just be that I am misunderstanding how to use this tool._

I ran the `analysis` tool and it resulted in an error after 44 minutes of running.

I checked the processing log but I don't know how to use the information it contains to troubleshoot the error.

I am hoping someone can point me in the right direction.

### Terminal Error Message

After running `analysis`, I received the following error message in Terminal:

<details>
<summary>Expand code block</summary>

```
# analysis US_Seattle_Urban_Villages_2023

Seattle (US_Seattle_Urban_Villages_2023)

Output directory:
  process/data/_study_region_outputs/US_Seattle_Urban_Villages_2023

A dated copy of project and region parameters has been saved as process/data/_study_region_outputs/US_Seattle_Urban_Villages_2023/_parameters.yml.

Analysis time zone: Australia/Melbourne (to set time zone for where you are,edit config.yml)

Analysis start: 2023-09-26_0452
Analyse neighbourhoods:              85%|█████████████████████████▍    | (11

Processing _11_neighbourhood_analysis.py failed: Command 'python
_11_neighbourhood_analysis.py US_Seattle_Urban_Villages_2023' returned non-
zero exit status 137.

 Please review the processing log file for this study region for more
information on what caused this error and how to resolve it. The file
__Seattle__US_Seattle_Urban_Villages_2023_processing_log.txt is located in
the output directory and may be opened for viewing in a text editor.
Analysis end:   2023-09-26_0535 (approximately 43.9 minutes)
```

</details>

### Processing Log

The last lines of the processing log file read as follows:

<details>
<summary>Expand code block</summary>

``` 
Processing completed at 2023-09-26_0503
- Task: create study region boundary
- Duration: 0.11 minutes

  - Set up simple nodes
  - Generate 1000m neighbourhoods for nodes (All pairs Dijkstra shortest path analysis)

                  :   0%|          | 0/131246 [00:00<?, ?nodes/s]
                  :   0%|          | 10/131246 [00:00<24:43, 88.44nodes/s]
                  :   0%|          | 26/131246 [00:00<17:22, 125.83nodes/s]
... (~5000 lines later)
                  :  61%|██████    | 80308/131246 [26:08<197:54:52, 13.99s/nodes]
                  :  61%|██████    | 80309/131246 [27:36<515:01:02, 36.40s/nodes]
                  :  61%|██████    | 80310/131246 [27:39<372:06:33, 26.30s/nodes]Killed

```
</details>

## Questions

1. Why was the process killed?
2. What was the process doing exactly?
3. Is this part of the analysis required or optional?
4. How would you recommend I try to resolve the error?

I would be happy to provide any additional information required to troubleshoot this error. 

Thanks in advance for your help.

**Comment by carlhiggs** [comment]
Hi @tiernanmartin , thanks for reaching out.

The 'Killed' message suggests an out-of-memory error; that's what happens when the Docker container runs out of allocated memory (e.g. as per [this](https://stackoverflow.com/questions/44417159/docker-process-killed-with-cryptic-killed-message) StackOverflow post).

That particular part of the script was doing a kind of pre-processing, for each node identifying all nodes reachable within 1000 metres; this is used for evaluating population and intersection density catchments.  This is more less illustrated in Figure 2 of
> Liu, S., Higgs, C., Arundel, J., Boeing, G., Cerdera, N., Moctezuma, D., Cerin, E., Adlakha, D., Lowe, M. and Giles-Corti, B. (2022), A Generalized Framework for Measuring Pedestrian Accessibility around the World Using Open Data. Geogr Anal, 54: 559-582. https://doi.org/10.1111/gean.12290  https://doi.org/10.48550/arXiv.2105.08814

or as code, [here](https://github.com/global-healthy-liveable-cities/global-indicators/blob/93220c8c7a76babf1908a7df00015be569abc8b0/process/subprocesses/_11_neighbourhood_analysis.py#L48-L132).

At this stage the analysis is more or less a complete process that does have to be successfully run through in order to produce indicator reports etc.  ie. all indicators are required to have successfully been produced.  In the future I plan to include updates to make it more user-configurable as to whcih indicators are processed, but for now there are other priorities (e.g. like getting your analysis running, and adding an FAQ entry on what to do if you have an out of memory error to provide guidance in cases like this).

So -- my first thought is resource allocation settings within Docker Desktop -- and how this is handled (and whether it is the issue) will depend on your system.
- https://docs.docker.com/desktop/settings/linux/
- https://docs.docker.com/desktop/settings/mac/
- https://docs.docker.com/desktop/settings/windows/

the specific part is 'memory'
> Memory. By default, Docker Desktop is set to use 2 GB of your host's memory. To increase the RAM, set this to a higher number; to decrease it, lower the number.

Can I ask, just so I know, what kind of computer your are running your analysis on? e.g. operating system (Mac, Win. Linux), RAM, etc

There used to be a setting within Docker Desktop to increase memory allocation, that was quite simple; but now, at least on my computer (Windows, running Windows Subsystem for Linux; WSL) its now handled by Windows as part of its WSL configuration.  I can't comment on Mac, and haven't checked how it works on dedicated Linux OS computers recently --- but I expect there will be directions at the above links.

I'm really interested to hear your computer specifications, and if you are able to find how to adjust the memory allocation for your system, if this helps.

Let me know how you go,

Carl

**Comment by carlhiggs** [comment]
Also, feel free to share your config file and I can see if I can replicate / test performance on my systems (a reasonably powerful desktop computer, and a low end laptop)

**Comment by tiernanmartin** [comment]
Thanks for the good guidance, @carlhiggs. 

Between your links and my trusty LLM sidekick, I was able to muddle through the steps needed to give my docker container more memory to work with. The analysis step successfully completed after about 40 minutes of running 🎉 

I'm working on a laptop PC with 16GB of RAM and 8 processors. The following`.wslconfig` file parameters worked for me:

```
[wsl2]
memory=12GB
processors=6
swap=4GB
```

<details>
<summary>More System Specs</summary>

|                            ITEM | VALUE                                                                                  |
|--------------------------------:|:----------------------------------------------------------------------------------------|
|                         OS Name | Microsoft Windows 11 Home                                                              |
|                         Version | 10.0.22621 Build 22621                                                                 |
|                    System Model | Surface Laptop 3                                                                       |
|                       Processor | Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz, 1498 Mhz, 4 Core(s), 8 Logical Processor(s) |
| Installed Physical Memory (RAM) | 16.0 GB                                                                                |

</details>

Thanks again for your help!
