### ISSUE TITLE
OSM validation literature review

### ISSUE THREAD

**Issue by DRosasMoctezuma** [healthysustainablecities/global-indicators#47]
We are opening an issue to document, propose, and discuss any prior literature work.

Which articles can help solidify the quality analysis framework for this project?

It would be helpful if everyone can add comments here regarding: 

- Discussion and proposal of previous literature work

- Quality assessments of OSM datasets literature

**Comment by DRosasMoctezuma** [comment]
The world's user-generated road map is more than 80% complete
https://journals.plos.org/plosone/article/file?id=10.1371/journal.pone.0180698&type=printable

Extending Processing Toolbox for assessing the logical consistency of OpenStreetMap data
https://onlinelibrary.wiley.com/doi/epdf/10.1111/tgis.12587

Quality Assessment of the French OpenStreetMap Dataset
https://onlinelibrary.wiley.com/doi/epdf/10.1111/j.1467-9671.2010.01203.x

A Comprehensive Framework for Intrinsic OpenStreetMap Quality Analysis
https://onlinelibrary.wiley.com/doi/epdf/10.1111/tgis.12073

How good is volunteered geographical information? A comprehensive study of OpenStreetMap and ordnance survey datasets
https://journals.sagepub.com/doi/pdf/10.1068/b35097

**Comment by carlhiggs** [comment]
There's a book on OpenStreetMap in GIScience from 2015 which contains a number of articles which may be relevent e.g. re data quality, inference of land use, and use in network routing:
https://link.springer.com/book/10.1007%2F978-3-319-14280-7
https://doi.org/10.1007/978-3-319-14280-7

This article looks at OSM validity with regard to neighbourhood socio-economic clustering (poorer neighbourhoods surrounded by other poor neighbourhoods had poorer representation of licensed liquor outlets in OSM than poorer neighbourhoods surrounded by wealthier neighbourhoods)
[Bright-2017-Geodemographic biases in crowdsour.pdf](https://github.com/gboeing/global-indicators/files/4768196/Bright-2017-Geodemographic.biases.in.crowdsour.pdf)

Bright J, De Sabbata S, Lee S. 2017. Geodemographic biases in crowdsourced knowledge websites: Do neighbours fill in the blanks? GeoJournal 83:427-440.

However, its worth noting in the above article that they considered counts which may present a more pessimistic representation of validity of OSM data when used in distance to closest analysis.  That is, even if in the real world POIs are clustered together but the count of these is under-represented in OSM, you only need at least one point in the approximate area to return an approximately accurate distance to closest estimate.  This hypothesis is linked to nature of spatial data, that like things cluster together -- so if for example we have one supermarket/restaurant/PT stop in our OSM data, we might actually expect more than one to be in the real world, as such things often cluster together (that is, if you were to bet where you would find some kind of amenity, you'd probably pick the place where other like amenities are located, not the place where you know none are --- kind of follow on implication from Tobler's first law of geography, if near things are more related than distant things, you'd expect to find more related things close to those things you are aware of even if the data you have doesn't represent them - particularly if you suspect your data to be indicative, but incomplete like OSM).  

This is why I think it would be worth us estimating the empirical difference between use of OSM and official datasets in addition to comparing the counts, as since we aren't measuring counts within distance but only distance to closest ---- we only need one valid point not multiple ones co-located to get an approximately right estimate of distance to closest.  (I suggested this somewhat earlier in the project, but not sure if we've looked into it to date).

There are also chapters on use and quality assessment of voluntary geographic information in the book 'Mapping and the Citizen  Sensor, downloadable from ubiquity press
https://www.ubiquitypress.com/site/books/10.5334/bbf/
![image](https://user-images.githubusercontent.com/12984626/84457059-07489500-aca5-11ea-87ca-158d5d5e3fc5.png)

**Comment by gboeing** [comment]
@DRosasMoctezuma in your 2nd comment above on this issue, can you edit to just link to those papers via DOIs rather than uploading the files to the issue?

Also this may be relevant: https://arxiv.org/pdf/1909.04323v1.pdf

**Comment by gboeing** [comment]
@DRosasMoctezuma can you make sure all of the material from this thread is in https://github.com/gboeing/global-indicators/issues/38#issuecomment-646872959? Thanks!

I'm going to close this issue in favor of consolidating at https://github.com/gboeing/global-indicators/issues/38#issuecomment-646872959
