### ISSUE TITLE
error dropping the existing study region database

### ISSUE THREAD

**Issue by shiqin-liu** [healthysustainablecities/global-indicators#475]
**Describe the bug**
As working with the Suzhou team, we are experimenting dropping an existing study region database, but having issues working with the subprocesses/_drop_study_region_database.py

**To Reproduce**
I try to run the script `python subprocesses/_drop_study_region_database.py Test_CN_Suzhou_2020`
but this error occurs:
```
# python subprocesses/_drop_study_region_database.py Test_CN_Suzhou_2020
Traceback (most recent call last):
  File "/home/ghsci/process/subprocesses/_drop_study_region_database.py", line 66, in <module>
    main()
  File "/home/ghsci/process/subprocesses/_drop_study_region_database.py", line 61, in main
    r = Region(codename)
        ^^^^^^
NameError: name 'Region' is not defined
```

**Additional context**
looks like it was due to this undefined `Region` in the function, I changed it to `r = ghsci.Region(codename)`, and it works. @carlhiggs any additional thoughts/suggestions for dropping the database? Happy to do the PR if this is the right direction

**Comment by carlhiggs** [comment]
Hi @shiqin-liu , I can look at this next week, but briefly, the way this usually works is you don't run that script directly, but rather as a function of the region object.  E.g.

'''
import ghsci
r=ghsci.Region(codename) 
r.drop()
'''

The reason it works directly on Region is because that is the argument passed to the function (i.e., the object r is passed, which is of the Region class).

I think it should work when used in this way? 

I think this may be a case of providing additional documentation on how to drop a study region.

For now, I think there may be some guidance if you enter, 

'''
r.help()
'''

Does this address the problem without need to modify code?

**Comment by carlhiggs** [comment]
Another thought is, we could modify that function so it could optionally be run at command line in the way you did (and perhaps that was the way I originally wrote it); that could avoid confusion for those who choose to run it in this way.  

But also, we should make it more clearly documented that the recommended approach is to run this directly as a sub-function of the ghsci.Region object (`r.drop()`).  For now, I believe that approach should work for the Suzhou team.  Let me know how you go!

**Comment by shiqin-liu** [comment]
@carlhiggs thanks for the clarification! Now I think it is clearer to me using the r.drop(). This should work with Suzhou team as we are trying the delete the imported OSM and start fresh. No necessary for the command line change then, but better documentation would be so helpful!

**Comment by carlhiggs** [comment]
Hi @shiqin-liu, I just updated the code (thanks for picking up on that edge case error there; it should work from command line as well as as a function of a `Region` object now.  Also, added in a new faq entry with directions on dropping and starting again [here](https://github.com/healthysustainablecities/global-indicators/wiki/Frequently-Asked-Questions-(FAQ)#drop-a-study-region-databaes-and-restart-an-analysis).  I'm sure we can refine later, but for now, hopefully its an improvement on documentation.  I'll close this issue now.
