### ISSUE TITLE
Validation Data Organization

### ISSUE THREAD

**Issue by DRosasMoctezuma** [healthysustainablecities/global-indicators#55]
I had a question regarding the validation data folders. During our meeting we discuss setting up the data on a root folder for the script to run (unzipping it first). I finished a script to unzip the data folders once the user downloads it to their own computer from the root folder. Do we need the script to be added to the main edge_validation py? Should we include all the data into different folders by city on CloudStor?

I have the following code: 

```python
import zipfile
from os import listdir, path

global_indicators_path = path.dirname(path.abspath(__file__))
edge_validation_data_path = path.join(global_indicators_path, "data", "edge_validation")
for city in listdir(edge_validation_data_path):
    with zipfile.ZipFile(path.join(edge_validation_data_path, city), "r") as zip_data:
        zip_data.extractall(path.join(edge_validation_data_path))
```

**Comment by gboeing** [comment]
cc @nicholas-david

**Comment by gboeing** [comment]
@DRosasMoctezuma thanks! A couple thoughts off the top of my head...

This script may be useful, though not necessary. I sometimes like to use scripts like this to simplify the downloading/extracting of archived data files that I don't want to keep on my local hard drive (especially if I'm in a folder in Dropbox or somesuch that soaks up personal cloud storage space).

However, I think this script sidesteps some of the benefits of data consolidation we had discussed on Monday's call. For example:

  1. It looks like it requires preexisting folder structure with city subfolders for the `listdir` call to work
  2. It looks like it expects a preexisting `edge_validation` folder in the data directory

Recall the goal of data consolidation was to have a single zip file of all our validation data (both edge and destination) zipped up into a single archive that preserves the entire folder structure beginning at the top-level `/data/` folder. The purpose is that no one would need any preexisting folder structure on their computer, or even a preexisting `/validation/data/` folder.

Instead, you'd just download the validation_data.zip file from cloudstor, place it in the `validation` folder on your computer, unzip it, and ta-da you automatically have a `/validation/data/` folder with all the structure and files expected by the validation scripts.

So rather than a zip extraction script, could you just consolidate all the data folders and files (coordinate with Nick, given his reorganization work) then zip them up so that the process described in the preceding paragraph would "just work?" Then coordinate with @carlhiggs to replace the current cloudstor validation files with this single consolidated zip archive.

@carlhiggs @nicholas-david please weigh in too if this plan makes sense for simplifying the validation data/structure.

**Comment by gboeing** [comment]
Looking at the folder structure on cloudstor, it might be even easier than that...

Let's say the process for getting the data becomes you just log into cloudstor, click "download", then extract that zip's contents to /validation/data/. @DRosasMoctezuma then you'd just have to update all the validation config files to point to the correct locations in that structure that already exists.

This is probably the best way to do it. Anyone disagree?
