### ISSUE TITLE
Olomouc Official Edge Data

### ISSUE THREAD

**Issue by nicholas-david** [healthysustainablecities/global-indicators#56]
David and I have been looking through the data on Cloudstor, and we are unable to find the official data for Olomouc's edges. For Olomouc's official data, we were only able to find supermarket destination data. Is anyone able to send the original official data for Olomouc?

@gboeing @carlhiggs

**Comment by gboeing** [comment]
I see it on cloudstor...

Go to the URL for "Official Data for Phase II Validation" then browse to `/edge validation/Olomouc/olomouc_edges.*`

**Comment by nicholas-david** [comment]
@gboeing It seems that is not the official data. From the OSM geopackage, we were unable to load the edges for some reason. We were able to load the sample points as a proxy to the edges.

When plotting the sample points and the data from  /edge validation/Olomouc/olomouc_edges.* , they still matched up perfectly, leading us to believe that  /edge validation/Olomouc/olomouc_edges.* is actually the OSM data. 

If you would like, I am available to call until 3:30pm. 

@gboeing

**Comment by gboeing** [comment]
@nicholas-david ah, got it. Ok that's a question for @carlhiggs then...

Carl, the "official" Olomouc edges shapefile on cloudstor is a perfect 1:1 match with the OSM edges data. This leads us to believe that it is not the true official data, but is simply a mislabeled copy of the OSM edges data. Can you double-check this for us, and perhaps update the "official" edges on cloudstor with the correct official shapefile if this is indeed the problem?

**Comment by carlhiggs** [comment]
Hi all, 

I'm not sure what is up with the data that is there, but I have just uploaded the original zip file provided by the collaborator Jan Dygryn for Olomouc street network data.  I also uploaded the street network data which was uploaded for Hanoi --- there may be good reasons this wasn't used previously, but in case it was overlooked I thought it worth also locating this in the edges folder since it is an asset we have to hand.

As far as I can tell the olomouc_edges shape file is what was provided by Thu on Google Drive:
![image](https://user-images.githubusercontent.com/12984626/85805679-522bd780-b790-11ea-8b25-4887cf904f27.png)

There was some back and forth regarding file names I recall, and perhaps things got mixed up then.  In any case, its best to have the original source file in the format and name as it was provided for posterity I think.

Hope this helps,

Carl

**Comment by gboeing** [comment]
@nicholas-david can you check these new files from Carl? If the Olomouc edges still look wrong, we can follow-up with Thu to see if she has the originals and got things mixed up on her end.

**Comment by DRosasMoctezuma** [comment]
@gboeing I'll take a look at the Olomouc data.

**Comment by carlhiggs** [comment]
I can confirm that the collaborator provided data appears different to that provided in the olomouc_edges.shp file --- on cloudstor and google drive the file sizes of that shapefile are in accord; however, they are much larger than those of the official network data:

![image](https://user-images.githubusercontent.com/12984626/85806119-881d8b80-b791-11ea-83bb-27a696367845.png)

Without looking at the data, I think this makes sense that the network labelled as 'olomouc_edges' is the OSMnx derived all roads dataset --- in particular, because its file sizes matches this shape file:
![image](https://user-images.githubusercontent.com/12984626/85806197-b4d1a300-b791-11ea-8cb3-f736444736a4.png)

The file size differences make sense, as Olomouc is small, but the OSM dataset has a 10km buffer to it - so is much larger.

**Comment by gboeing** [comment]
@carlhiggs thanks for tracking this down. Given that you appear to have the *correct* official Olomouc edges shapefile on your hard drive, would you mind uploading to the cloudstor validation data folder and replacing the incorrect edges shapefile there?

**Comment by carlhiggs** [comment]
Hi @gboeing , assuming you are refering to the zip file provided by Jan Dygryn, I posted it on Cloudstor before making my initial post above.
![image](https://user-images.githubusercontent.com/12984626/85914867-a95fa400-b885-11ea-8c4b-a525c0b3d5bd.png)

Please let me know if I'm misunderstanding what you mean, but I think this is what you are asking for and it is already there.  I assume Thu was using this file previously, but when changing file names / uploading to Google drive it must have been mixed up with the OSM data.  (I assume you don't want the OSM data re-uploaded, as I believe that is there too?)

Enjoy the weekend,

Carl

**Comment by carlhiggs** [comment]
I didn't remove the previous file that appears incorrect 'olomouc_edges' - and I don't think its necessarily a good idea to rename the official data to match that name construct.  I or others can delete this once what you need is sorted (I believe you all have edit and upload privileges).

**Comment by gboeing** [comment]
Ah yes thanks Carl. I missed that detail earlier in my haste. Sorry.

@DRosasMoctezuma can you check that data file on Monday (by running the edge validation script with all the correct data files now) and verify we're all good now?

**Comment by DRosasMoctezuma** [comment]
Thank you @carlhiggs @gboeing I will check the data file prior to our Monday meeting.

**Comment by gboeing** [comment]
@DRosasMoctezuma thanks. Remember we pushed our team meeting to Tuesday next week.
